### ISSUE TITLE
npm ko-reactor version is stuck at 1.3.7

### ISSUE THREAD

**Issue by sudsy** [ZiadJ/knockoutjs-reactor#42]
Might need to update that with a publish

**Comment by bago** [comment]
THe user "rcmax" has the privileges on the ko-rector name on npm repository, so we can't do anything.

Either rcmax shares permissions or we move to another name (e.g: knockoutjs-reactor) also for the npm package.

@ZiadJ what do you think about renaming the package to knockoutjs-rector so that npm name matches the github repository name? Then we could release 1.4.0 with the new name.

**Comment by sudsy** [comment]
Not Sure if this helps [npm disputes](https://docs.npmjs.com/misc/disputes)

**Comment by ZiadJ** [comment]
@bago knockoutjs-reactor is fine as long as it shows up when searching with keywords like 'knockout reactor'.

**Comment by W3Max** [comment]
Sorry about that. I'll give you back the ownership of the npm package. Can you just give me your npm username?

**Comment by bago** [comment]
My npm username is bago75

**Comment by RCMax** [comment]
@bago done!

**Comment by bago** [comment]
Just published 1.3.9 and 1.4.0-beta!
